language: java
sudo: true
dist: trusty
before_install:
  - chmod +x mvnw
git:
  depth: false
cache:
  directories:
    - "$HOME/.m2"
install: true
matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: openjdk12
    - os: linux
      jdk: openjdk13
    - os: linux
      jdk: openjdk14
script:
  - "git clone https://github.com/XenoAmess/commonx_additional_tests.git"
  - "cp -frap ./commonx_additional_tests/src/test/* ./src/test/ "
  - "./mvnw clean install -U -Dmaven.javadoc.skip=false"
  - "if [ \"$TRAVIS_JDK_VERSION\" = \"openjdk12\" ]; then ./mvnw sonar:sonar -Dsonar.projectKey=commonx -Dsonar.organization=xenoamess-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.log.level=DEBUG -Dsonar.sources=src/main/java -Dsonar.language=java -Dsonar.java.source=1.8 -Dsonar.sourceEncoding=UTF-8 -Dsonar.java.binaries=target/classes/ -Dsonar.java.test.binaries=target/test-classes/ -Dsonar.tests=src/test/ -Dsonar.java.coveragePlugin=jacoco -Dsonar.jacoco.reportPaths=target/jacoco.exec -Dsonar.junit.reportPaths=target/surefire-reports/ -Dsonar.login=98a6d1650ab33a15e5843ce5e5f50f53bc775e49 ; fi"